auto-commits: false
show-model-warnings: false
analytics: false
gitignore: false
auto-lint: true
multiline: true
# model: openrouter/google/gemini-2.5-pro-preview-03-25
model: openrouter/google/gemini-2.5-flash-preview
# model: openrouter/meta-llama/llama-4-maverick:free
# model: xai/grok-3-mini-fast-beta # fast but stupid
################## this for grok-3-fast-beta - it needs thinking and screws up edit-format
model: xai/grok-3-fast-beta
reasoning-effort: high
edit-format: full
################## this for grok-3-fast-beta - it needs thinking and screws up edit-format
# architect: true
# read:
file:
  - ./README.md
  - ./background.js
  - ./chat.css
  - ./chat.html
  - ./chat.js
  - ./constants.js
  - ./floatingIcon.js
  - ./highlighter.js
  - ./manifest.json
  - ./options.css
  - ./options.html
  - ./options.js
  - ./pageInteraction.css
  - ./pageInteraction.js
  - ./summaryPopup.js
  - ./utils.js
read:
  - ./CONVENTIONS.md
  - ./marked.min.js
  - ./country-flags/languages.json
  - ./icons/icon128.png
  - ./icons/icon48.png
  - ./icons/icon16.png
  - ./icons/icon.svg
