- name: openrouter/anthropic/claude-3.7-sonnet
  extra_params:
    use_temperature: 0
    extra_body:
      provider:
        # Only use these providers, in this order
        order: ["Anthropic", "Together"]
        # Don't fall back to other providers
        allow_fallbacks: false
        # Skip providers that may train on inputs
        # data_collection: "deny"
        # Only use providers supporting all parameters
        require_parameters: true

- name: openrouter/deepseek/deepseek-r1
  extra_params:
    use_temperature: 0
    extra_body:
      provider:
        # Only use these providers, in this order
        order: ["SambaNova"]
        # Don't fall back to other providers
        allow_fallbacks: false
        # Skip providers that may train on inputs
        # data_collection: "deny"
        # Only use providers supporting all parameters
        require_parameters: true

- name: openrouter/google/gemini-2.5-flash-preview
  extra_params:
    use_temperature: 0
  # edit_format: whole
  # edit_format: diff
  use_repo_map: true
  accepts_settings:
    - thinking_tokens

# - name: xai/grok-3-fast-beta
#   extra_params:
#     use_temperature: 0
